M48
; DRILL file {KiCad 7.0.9} date Wednesday, December 06, 2023 at 02:48:16 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-06T14:48:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.675Y-2.65
X1.725Y-0.75
X3.725Y-1.35
X3.725Y-2.45
T0
M30
